recipe_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view, welcome_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcome_view, name='welcome'),
    path('recipes/', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('home', views.RecipeListView.as_view(), name='home'),
    path('search', views.search_view, name='recipes_search'),
    path('analytics', views.charts_view, name='charts_search'),
    path('create', views.create_recipe, name ='create_recipe'),
    path('<pk>', views.RecipeDetailView.as_view(), name='detail')
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

class Choices:
    difficulty_choices = (
        ('E', 'Easy'),
        ('M', 'Medium'),
        ('I', 'Intermediate'),
        ('H', 'Hard')
    )


class Recipe(models.Model):
    recipe_name = models.CharField(max_length = 50, verbose_name='Recipe Name')
    ingredients = models.CharField(max_length = 200, verbose_name='Ingredients')
    cooking_time = models.FloatField(help_text='in minutes', verbose_name='Cooking Time')
    difficulty = models.CharField(max_length=15, choices=Choices().difficulty_choices, default='E')
    pic = models.ImageField(upload_to='recipes', default='no-picture.jpg', blank=True, null=True)
    note = models.TextField(blank=True, verbose_name='Note')

    def __str__(self):
        return self.recipe_name

    
    def get_absolute_url(self):
       return reverse('recipes:detail', kwargs={'pk': self.pk})

recipes/forms.py
from django import forms
from .models import Recipe

CHART_CHOICES = {
    ('bar', 'Bar Chart'),
    ('pie', 'Pie Chart'),
    ('line', 'Line Chart')
}

DIFFICULTY_CHOICES = (
    ('', 'All'),
    ('E', 'Easy'),
    ('M', 'Medium'),
    ('I', 'Intermediate'),
    ('H', 'Hard')
)

class SearchRecipeForm(forms.Form):
    recipe_name = forms.CharField(max_length = 120, required=False)
    ingredient = forms.CharField(max_length = 20, required=False)
    difficulty = forms.ChoiceField(choices = DIFFICULTY_CHOICES, required=False)
    max_cooking_time = forms.FloatField(required=False)
    min_cooking_time = forms.FloatField(required=False)

class DataVisualizationForm(forms.Form):
    chart_type = forms.ChoiceField(choices = CHART_CHOICES, required=False)

class CreateRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['recipe_name', 'ingredients', 'cooking_time', 'difficulty', 'pic', 'note', ]

recipe_app/views.py
from django.shortcuts import render, redirect  
#Django authentication libraries           
from django.contrib.auth import authenticate, login
#Django Form for authentication
from django.contrib.auth.forms import AuthenticationForm  
from django.contrib.auth import authenticate, login, logout
#to protect function-based views
from django.contrib.auth.decorators import login_required

def login_view(request):
    error_message = None  
    form = AuthenticationForm()

    if request.method == "POST":                       
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():                                
            username = form.cleaned_data.get('username') 
            password = form.cleaned_data.get('password') 
            user = authenticate(username = username, password = password)
            if user is not None:                    
                login(request, user)                
                return redirect('recipes:home')
        else:  
            error_message = 'ooops.. something went wrong'

    context ={                                             
        'form': form, 
        'error_message': error_message     
    }
    return render(request, 'auth/login.html', context)     
        
    
@login_required
def logout_view(request):
    logout(request)
    return render(request, 'auth/success.html')

def welcome_view(request):
    return render(request, 'welcome/recipes_home.html')

recipes/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import SearchRecipeForm, DataVisualizationForm
import pandas as pd
from .utils import get_chart, get_all_ingredients
from .forms import CreateRecipeForm

@login_required
def search_view(request):
    if request.method == 'POST':
        form = SearchRecipeForm(request.POST)
        if form.is_valid():
            filters = {}
            recipe_name = form.cleaned_data.get('recipe_name')
            ingredient = form.cleaned_data.get('ingredient')
            difficulty = form.cleaned_data.get('difficulty')
            max_cooking_time = form.cleaned_data.get('max_cooking_time')
            min_cooking_time = form.cleaned_data.get('min_cooking_time')

            if recipe_name:
                filters['recipe_name__icontains'] = recipe_name
            if ingredient:
                filters['ingredients__icontains'] = ingredient
            if difficulty:
                filters['difficulty'] = difficulty
            if max_cooking_time:
                filters['cooking_time__lte'] = max_cooking_time
            if min_cooking_time:
                filters['cooking_time__gte'] = min_cooking_time

            recipes = Recipe.objects.filter(**filters)
            print('Recipes: ', recipes)
            return render(request, 'recipes/recipes_search.html', {'recipes': recipes, 'form': form})
    else:
        form = SearchRecipeForm()
    return render(request, 'recipes/recipes_search.html', {'form': form})

@login_required
def charts_view(request):
    form = DataVisualizationForm(request.POST or None)
    recipes_df = None
    chart = None
    if request.method =='POST':
       chart_type = request.POST.get('chart_type')

       #apply filter to extract data
       qs = Recipe.objects.all()
       if qs: #if data found
           #convert the queryset values to pandas dataframe
           recipes_df=pd.DataFrame(qs.values()) 
           all_ingredients = get_all_ingredients()
           #call get_chart by passing chart_type from user input, sales dataframe and labels
           chart=get_chart(chart_type, recipes_df, all_ingredients)
           #convert the dataframe to HTML
           recipes_df=recipes_df.to_html()

    context = {
        'form': form,
        'recipes_df': recipes_df,
        'chart': chart
    }

    return render(request, 'recipes/recipes_analytics.html', context)

@login_required
def create_recipe(request):
    if request.method == 'POST':
        form = CreateRecipeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('recipes:home')
    else:
        form = CreateRecipeForm()
    return render(request, 'recipes/recipes_create.html', {'form': form})

class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/recipes_list.html'

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/recipes_detail.html'

recipe_app/recipes/templates/recipes/home.html
<!DOCTYPE html>

<html>
    <head>
        <title>
            Welcome to Recipes
        </title>
    </head>

    <body>
        <h1>
            Welcome to the Recipe Lounge
        </h1>
    </body>
</html>

recipe_app/recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Insatiable</title>
        <link rel="stylesheet" href="../../static/recipes/css/recipe_home.css" >
    </head>

    <body>
        <section class = "hero-banner">
            <h1 class = "hero-banner-title">Insatiable</h1>
            <div class = "intro">
                <b><p>Welcome to Insatiable. The food app that never stops.</p></b>
                <button onClick="document.getElementById('main-section').scrollIntoView()">Browse our recipes</button>
                <a href="#">
                    <button>Add a new recipe</button>
                </a>
            </div>
            <br/>
            
        </section>

        <section class = "main-recipe-section" id="main-section">
            <h1>Recipe List</h1>
            <div class = "recipe-list">
                {% for recipe in recipe_list %}
                    <div class="recipe-square">
                        <a href="{{recipe.get_absolute_url}}">
                            <img src="{{recipe.pic.url}}" class = "recipe-image" />
                            <h2 class="recipe-image-caption">{{recipe.recipe_name}}</h2>
                        </a>
                    </div>
                    
                {% endfor %}
            </div>
        </section>

        <section class = "footer">

        </section>
    </body>
</html>

recipes/templates/recipes/recipes_analytics.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Recipe Search</title>
    <link rel="stylesheet" href="../../static/recipes/css/recipe_search.css">
</head>
<body>
    <section class = "navbar">
        <a href="/recipes/home">
            <button>Home</button>
        </a>
        <a href ="{%url 'logout' %}"> 
            <button>Logout</button>  
        </a>
    </section>

    <div class="data-analytics">
        <h1>Data Analytics</h1>
        <hr>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.chart_type }}
            <button type="submit">Generate Analytics</button>
        </form>

        <br>

        {% if recipes_df %}
            <img src="data:image/png;base64, {{chart|safe}}">
        {% else %}
            <h3>No data</h3>
        {% endif %}
    </div>
</div>
</body>
</html>

recipes/templates/recipes/recipes_create.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add New Recipe</title>
    <link rel="stylesheet" href="../../static/recipes/css/recipe_search.css">
</head>
<body>
    <section class = "navbar">
        <a href="/recipes/home">
            <button>Home</button>
        </a>
        <a href ="{%url 'logout' %}"> 
            <button>Logout</button>  
        </a>
    </section>
    <h1>Add a Recipe:</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Recipe</button>
    </form>
</body>
</html>

recipes/templates/recipes/recipes_detail.html
<!DOCTYPE html>

<html>

    <head>
        <title>{{object.name}}</title>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="../../static/recipes/css/recipe_detail.css" >
    </head>

    <body>
        <section class = "navbar">
            <a href="/recipes/home">
                <button>Home</button>
            </a>
            <a href ="{%url 'logout' %}"> 
                <button>Logout</button>  
            </a>
            <form method="get" action="{% url 'recipes:recipes_search' %}">
                {{ form.as_p }}
                <button type="submit">Search</button>
            </form>
            <form method="get" action="{% url 'recipes:charts_search' %}">
                {{ form.as_p }}
                <button type="submit">Analytics</button>
            </form>
            <form method="get" action="{% url 'recipes:create_recipe' %}">
                {{ form.as_p }}
                <button type="submit">Add New Recipe</button>
            </form>
        </section>


        <div class = "recipe-card">
            <div class = "recipe-card-content">
                <div class = "recipe-card-details">
                    <h1 class = "recipe-card-title">{{object.recipe_name}}</h1>
                    <b>Ingredients: <br/> </b> {{object.ingredients}} <br>
                    <b>Cooking Time: </b> {{object.cooking_time}} minutes<br>
                    <b>Difficulty: </b> {{object.get_difficulty_display}} <br>
                    <b>Notes: </b> <p>{{object.note}}</p> <br>
                    <a href="/recipes/home">
                        <button>Home</button>
                    </a>
                    <a href="/recipes/search">
                        <button>Search</button>
                    </a>
                </div>
                <div class = "recipe-card-image">
                    <img src="{{object.pic.url}}"/> <br>
                </div>
            </div>

        <div>

    </body>

</html>

recipes/templates/recipes/recipes_list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Insatiable</title>
        <link rel="stylesheet" href="../../static/recipes/css/recipe_list.css" >
    </head>

    <body>
        <section class = "navbar">
            <a href="/recipes/home">
                <button>Home</button>
            </a>
            <a href ="{%url 'logout' %}"> 
                <button>Logout</button>  
            </a>
            <form method="get" action="{% url 'recipes:recipes_search' %}">
                {{ form.as_p }}
                <button type="submit">Search</button>
            </form>
            <form method="get" action="{% url 'recipes:charts_search' %}">
                {{ form.as_p }}
                <button type="submit">Analytics</button>
            </form>
            <form method="get" action="{% url 'recipes:create_recipe' %}">
                {{ form.as_p }}
                <button type="submit">Add New Recipe</button>
            </form>
        </section>

        <section class = "main-recipe-section" id="main-section">
            <h1>Recipe List</h1>
            <div class = "recipe-list">
                {% for recipe in recipe_list %}
                    <div class="recipe-square">
                        <a href="{{recipe.get_absolute_url}}">
                            <img src="{{recipe.pic.url}}" class = "recipe-image" />
                            <h2 class="recipe-image-caption">{{recipe.recipe_name}}</h2>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </section>
        <section class = "footer">
            <h3>About the developer</h3>
            <p>Jeriko Carrera is a Full-Stack Web Developer with a love for Python and JavaScript.</p>
            <p>Come learn more about him <a href = "https://carrerajeriko.com" target="_blank" rel="noreferrer"> here: </a>
        </section>
    </body>
</html>

recipes/templates/recipes/recipes_search.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Recipe Search</title>
    <link rel="stylesheet" href="../../static/recipes/css/recipe_search.css">
</head>
<body>
    <section class = "navbar">
        <a href="/recipes/home">
            <button>Home</button>
        </a>
        <a href ="{%url 'logout' %}"> 
            <button>Logout</button>  
        </a>
    </section>
    <form action="" method="POST">
        <h1>Search for Recipes</h1>
        {% csrf_token %}
        <div class="form-field">
            <label for="id_recipe_name">Recipe Name:</label>
            {{ form.recipe_name }}
        </div>
        <div class="form-field">
            <label for="id_ingredient">Ingredient:</label>
            {{ form.ingredient }}
        </div>
        <div class="form-field">
            <label for="id_difficulty">Difficulty:</label>
            {{ form.difficulty }}
        </div>
        <div class="form-field">
            <label for="id_min_cooking_time">Min Cooking Time (min):</label>
            {{ form.min_cooking_time }}
        </div>
        <div class="form-field">
            <label for="id_max_cooking_time">Max Cooking Time (min):</label>
            {{ form.max_cooking_time }}
        </div>
        <button type="submit">Search</button>
    </form>
       
    <div class="recipe-list">
        {% for recipe in recipes %}
            <div class="recipe-square">
                <a href="{{ recipe.get_absolute_url }}">
                    <img src="{{ recipe.pic.url }}" class="recipe-image" />
                    <h2 class="recipe-image-caption">{{ recipe.recipe_name }}</h2>
                </a>
            </div>
            {% empty %}
                <p>No recipes found.</p>
        {% endfor %}
    </div>
</body>
</html>

templates/welcome/recipes_home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Insatiable</title>
        <link rel="stylesheet" href="../../static/recipes/css/recipe_home.css">
    </head>

    <body>
        <section class = "hero-banner">                                                                                                                                                                                                                                             
            <h1 class = "hero-banner-title">Insatiable</h1>
            <div class = "intro">
                <p>Welcome to <b>Insatiable</b>. The food app that never stops.</p>
                <a href ="{%url 'login' %}">
                    <button>Login</button> 
                </a>
            </div>
        </section>
    </body>
</html>